#!/usr/bin/env bash
# seed-user-home.sh — copy bundled VLE notebooks + DB into ~/work on first start.
#
# DockerSpawner mounts a persistent named volume at ~/work. The very first time
# a user logs in, that volume is empty. This hook populates it with the copies
# baked into /opt/vle at image build time. On every subsequent start it is a
# no-op, so users can edit their own copies freely.
#
# The jupyter/docker-stacks base image *sources* everything under
# before-notebook.d/ from its start.sh rather than exec'ing it, so any shell
# options we set leak into the parent. In particular `set -u` would crash
# start.sh on its own unset variables (e.g. JUPYTER_DOCKER_STACKS_QUIET).
# Keep the whole body inside a subshell so strict mode stays strict here and
# does not escape to the caller.

(
  set -euo pipefail

  WORK="${HOME}/work"
  mkdir -p "${WORK}"

  if [[ ! -d "${WORK}/notebooks" ]] && [[ -d /opt/vle/notebooks ]]; then
    cp -r /opt/vle/notebooks "${WORK}/notebooks"
  fi

  # index.ipynb is auto-generated by scripts/build_index.py on every deploy,
  # so always refresh it — users are not expected to edit the landing page.
  # Any other notebook is preserved once it has been seeded so user edits
  # survive.
  if [[ -f /opt/vle/notebooks/index.ipynb ]]; then
    mkdir -p "${WORK}/notebooks"
    cp /opt/vle/notebooks/index.ipynb "${WORK}/notebooks/index.ipynb"
  fi

  if [[ ! -f "${WORK}/data/components.db" ]] && [[ -f /opt/vle/data/components.db ]]; then
    mkdir -p "${WORK}/data"
    cp /opt/vle/data/components.db "${WORK}/data/components.db"
  fi
)
