#!/usr/bin/env bash
# seed-user-home.sh — seed bundled VLE notebooks + DB into ~/work.
#
# DockerSpawner mounts a persistent named volume at ~/work. Behavior:
#
#   - First spawn (empty ~/work): full seed of /opt/vle/notebooks/
#     and /opt/vle/data/components.db into ~/work/.
#   - Subsequent spawns: no-op UNLESS the deploy stamped a new value into
#     /opt/vle/notebooks/.notebook-version that doesn't match the user's
#     copy at ~/work/notebooks/.notebook-version. In that case we re-seed
#     every *managed* notebook (= every .ipynb in /opt/vle/notebooks/).
#     User-created notebooks under different paths are preserved.
#
# Re-seed semantics (NOTEBOOK-VERSION-RESEED-v1): a version bump
# OVERWRITES the user's copy of any managed notebook. Edits to bundled
# notebooks are NOT preserved across a version bump — the hub-sandbox
# notice in every notebook tells users to "Save As" to a different
# filename if they want their edits to survive a refresh. Files outside
# the managed set (the user's own .ipynb, datasets, scratch dirs) are
# never touched.
#
# The jupyter/docker-stacks base image *sources* everything under
# before-notebook.d/ from its start.sh rather than exec'ing it, so any
# shell options we set leak into the parent. In particular `set -u` would
# crash start.sh on its own unset variables (e.g. JUPYTER_DOCKER_STACKS_QUIET).
# Keep the whole body inside a subshell so strict mode stays strict here
# and does not escape to the caller.
#
# SUBSHELL-WRAPPER-v1  ← sentinel grepped by deploy/scripts/deploy.sh to
# confirm this file made it into the built notebook image. Do not remove.
# NOTEBOOK-VERSION-RESEED-v1 ← sentinel for the version-marker logic.

(
  set -euo pipefail

  WORK="${HOME}/work"
  WORK_NB="${WORK}/notebooks"
  BUNDLED_NB="/opt/vle/notebooks"
  mkdir -p "${WORK}"

  # ---- First-spawn full seed -----------------------------------------------
  if [[ ! -d "${WORK_NB}" ]] && [[ -d "${BUNDLED_NB}" ]]; then
    cp -r "${BUNDLED_NB}" "${WORK_NB}"
  fi

  # ---- index.ipynb always refreshes ---------------------------------------
  # Auto-generated by scripts/build_index.py on every deploy; users are not
  # expected to edit it.
  if [[ -f "${BUNDLED_NB}/index.ipynb" ]]; then
    mkdir -p "${WORK_NB}"
    cp "${BUNDLED_NB}/index.ipynb" "${WORK_NB}/index.ipynb"
  fi

  # ---- Version-marker re-seed ---------------------------------------------
  # If the deploy stamped a new value into the bind-mounted notebooks
  # directory, overwrite each managed notebook in the user's volume.
  # Comparison is a plain string match; no version-format assumptions.
  BUNDLED_VER_FILE="${BUNDLED_NB}/.notebook-version"
  USER_VER_FILE="${WORK_NB}/.notebook-version"
  if [[ -f "${BUNDLED_VER_FILE}" ]]; then
    BUNDLED_VER="$(cat "${BUNDLED_VER_FILE}")"
    USER_VER="$(cat "${USER_VER_FILE}" 2>/dev/null || echo "")"
    if [[ "${USER_VER}" != "${BUNDLED_VER}" ]]; then
      mkdir -p "${WORK_NB}"
      # Iterate via a glob so we don't choke on shells without `shopt -s
      # nullglob`. If the glob has no matches we'd see the literal pattern
      # — the [[ -f ]] guard handles that case.
      for nb in "${BUNDLED_NB}"/*.ipynb; do
        [[ -f "${nb}" ]] || continue
        cp "${nb}" "${WORK_NB}/"
      done
      printf '%s\n' "${BUNDLED_VER}" > "${USER_VER_FILE}"
    fi
  fi

  # ---- Component database (first-spawn only) ------------------------------
  if [[ ! -f "${WORK}/data/components.db" ]] && [[ -f /opt/vle/data/components.db ]]; then
    mkdir -p "${WORK}/data"
    cp /opt/vle/data/components.db "${WORK}/data/components.db"
  fi
)
