"""Bundled component database — JSON-backed pure-component property lookup.

This module is the read side of the component database that ships *inside*
the wheel (``vle/data/components.json``, generated by
``scripts/build_components_json.py``). It is intentionally tiny and
dependency-free: where :mod:`vle.db` is a full SQLite store (writable, with
kij / activity / experimental tables), this module is a frozen, read-only
lookup that the high-level :class:`vle.System` uses to turn a component
*name* into the numbers the Rust engine needs.

**Units** (canonical engine units throughout — see ``CLAUDE.md``):

- ``tc`` — critical temperature, **K**
- ``pc`` — critical pressure, **kPa** (absolute)
- ``omega`` — acentric factor (dimensionless)
- ``zc`` — critical compressibility factor (dimensionless)
- ``vc`` — critical molar volume, **cm³/mol**
- ``tb`` — normal boiling temperature, **K**
- ``mw`` — molar mass, **g/mol**
- ``liquid_volume`` — saturated-liquid molar volume near 298 K, **cm³/mol**
- ``psat_coeffs`` — reduced Antoine ``ln(Psat/Pc) = a1 − a2/(a3 + T)`` with
  T in **K** (so ``Psat`` comes out in the same units as ``pc``, kPa)
- ``cp_coeffs`` — dimensionless ideal-gas ``Cp°/R = Σₖ aₖ·Tᵏ`` polynomial,
  T in **K** (matches the engine convention; empty ⇒ no ideal-Cp data)

Example
-------
>>> from vle.components import get, available
>>> water = get("water")
>>> water.tc, water.pc
(647.096, 22064.0)
>>> "benzene" in available()
True
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache

# ``importlib.resources`` reads a data file that lives *inside* the installed
# package, whether that package is an unzipped directory or a zipped wheel on
# ``sys.path``. Using it (rather than ``open(__file__/..)``) is what makes the
# bundled JSON survive being packaged into the wheel.
from importlib.resources import files


@dataclass(frozen=True)
class Component:
    """One pure component's constant properties (canonical engine units).

    Frozen (immutable) so a looked-up record can't be mutated in place and
    silently diverge from the bundled database. Build a modified copy with
    :func:`dataclasses.replace` if you need a tweaked component.

    All physical fields carry the units documented at the module level.
    ``psat_coeffs`` is the 3-entry reduced-Antoine coefficient list; an
    empty list means "no vapor-pressure correlation shipped for this
    component" (the engine then falls back to whatever the EOS provides).

    ``cp_coeffs`` is the 5-entry dimensionless ideal-gas Cp°/R polynomial
    ``Cp°(T)/R = Σₖ aₖ·Tᵏ`` (T in **K**, R = 8.31451 kJ/(kmol·K)), matching
    the engine convention; an empty list means "no ideal-Cp data" and the
    engine treats the ideal-gas heat-capacity contribution as zero.
    ``cp_t_range`` is the ``[t_min, t_max]`` K validity window of that fit.
    """

    name: str
    formula: str = ""
    cas: str = ""
    mw: float = 0.0
    tc: float = 0.0  # K
    pc: float = 0.0  # kPa (abs)
    omega: float = 0.0
    zc: float = 0.0
    vc: float = 0.0  # cm³/mol
    tb: float = 0.0  # K
    psat_coeffs: list[float] = field(default_factory=list)
    liquid_volume: float = 0.0  # cm³/mol at ~298 K
    psat_source: str = ""
    cp_coeffs: list[float] = field(default_factory=list)  # Cp°/R = Σ aₖ Tᵏ, T in K
    cp_t_range: list[float] = field(default_factory=list)  # [t_min, t_max] K
    cp_source: str = ""


@lru_cache(maxsize=1)
def _raw() -> dict:
    """Load and cache the bundled JSON once per process.

    ``lru_cache`` memoizes the parse so repeated ``get`` calls don't re-read
    or re-parse the file. ``files(...)`` returns a traversable pointing at
    the packaged resource; ``.read_text`` works on both a directory install
    and a zipped wheel.
    """
    text = files("vle.data").joinpath("components.json").read_text(encoding="utf-8")
    return json.loads(text)


def _compounds() -> dict:
    return _raw()["compounds"]


def available() -> list[str]:
    """Return the sorted list of component names in the bundled database."""
    return sorted(_compounds().keys())


def _to_component(name: str, entry: dict) -> Component:
    """Build a :class:`Component` from one JSON entry, ignoring extra keys."""
    fields = {f for f in Component.__dataclass_fields__}
    kwargs = {k: v for k, v in entry.items() if k in fields}
    return Component(name=name, **kwargs)


def get(name: str) -> Component:
    """Look up a component by name (case-insensitive).

    Args:
        name: Component name, e.g. ``"water"`` or ``"n-Butane"``.

    Returns:
        The :class:`Component` record (canonical engine units).

    Raises:
        KeyError: If no component with that name is in the bundled database.
            The message lists the available names to make typos obvious.
    """
    compounds = _compounds()
    # Case-insensitive: build a lowercase index once (cheap; dict is small).
    lowered = {k.lower(): k for k in compounds}
    key = lowered.get(name.strip().lower())
    if key is None:
        raise KeyError(
            f"unknown component {name!r}; available: {', '.join(available())}"
        )
    return _to_component(key, compounds[key])


def search(query: str) -> list[Component]:
    """Return every component whose name, formula, or CAS contains ``query``.

    Case-insensitive substring match. Useful for interactive discovery,
    e.g. ``search("butane")`` or ``search("C4")``.
    """
    q = query.strip().lower()
    out = []
    for name, entry in sorted(_compounds().items()):
        haystack = f"{name} {entry.get('formula', '')} {entry.get('cas', '')}".lower()
        if q in haystack:
            out.append(_to_component(name, entry))
    return out


def all_components() -> list[Component]:
    """Return every component in the bundled database, name-sorted."""
    return [_to_component(n, e) for n, e in sorted(_compounds().items())]
