#!/usr/bin/env python
"""Send a prompt file to an external model and record the answer verbatim.

Deliberately dependency-free — stdlib ``urllib`` only, no ``openai`` package —
so it installs nothing into the ``vle`` conda environment. The API key is read
from 1Password at call time and never written to disk or echoed.

Usage (from the repo root)::

    ~/miniconda3/envs/vle/bin/python scripts/second_opinion.py \\
        docs/plans/engine/second-opinion/dualn-prompt.md \\
        --model gpt-5.6-sol --effort xhigh \\
        --out docs/plans/engine/second-opinion/dualn-response-sol.md

The response is written verbatim, with a provenance header carrying the model,
the reasoning effort, the token counts and the computed cost. Nothing is
edited: the point of the exercise is a record of what the model actually said,
including where it was wrong.

See ``docs/plans/engine/SECOND_OPINION_TRIAL.md``.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone

OP_REF = "op://Homelab/photo-platform-openai/credential"
ENDPOINT = "https://api.openai.com/v1/responses"

# USD per million tokens, from OpenAI's published pricing.
PRICING = {
    "gpt-5.6-sol": (5.00, 30.00),
    "gpt-5.6-terra": (2.00, 12.00),
    "gpt-5.6-luna": (0.20, 1.20),
}


def read_key() -> str:
    """Fetch the API key from 1Password. Never printed, never persisted."""
    try:
        key = subprocess.run(
            ["op", "read", OP_REF],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except subprocess.CalledProcessError as exc:
        sys.exit(f"1Password read failed: {exc.stderr.strip()}")
    if not key.startswith("sk-"):
        sys.exit("1Password returned something that is not an API key")
    return key


def ask(key: str, model: str, effort: str, prompt: str, max_output: int) -> dict:
    body = {
        "model": model,
        "input": prompt,
        "reasoning": {"effort": effort},
        "max_output_tokens": max_output,
    }
    req = urllib.request.Request(
        ENDPOINT,
        data=json.dumps(body).encode(),
        headers={
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=1800) as resp:
            return json.load(resp)
    except urllib.error.HTTPError as exc:
        sys.exit(f"HTTP {exc.code}: {exc.read().decode()[:2000]}")


def extract_text(payload: dict) -> str:
    """Pull the assistant text out of a Responses API payload."""
    chunks: list[str] = []
    for item in payload.get("output", []):
        if item.get("type") != "message":
            continue
        for part in item.get("content", []):
            if part.get("type") == "output_text":
                chunks.append(part.get("text", ""))
    return "\n".join(chunks)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("prompt", help="path to the prompt markdown file")
    ap.add_argument("--model", default="gpt-5.6-sol")
    ap.add_argument(
        "--effort",
        default="xhigh",
        choices=["none", "low", "medium", "high", "xhigh", "max"],
    )
    ap.add_argument("--max-output", type=int, default=32000)
    ap.add_argument("--out", required=True, help="where to write the response")
    args = ap.parse_args()

    prompt = open(args.prompt).read()
    print(f"prompt: {len(prompt):,} chars -> {args.model} (effort={args.effort})")

    payload = ask(read_key(), args.model, args.effort, prompt, args.max_output)

    text = extract_text(payload)
    usage = payload.get("usage", {})
    tin, tout = usage.get("input_tokens", 0), usage.get("output_tokens", 0)
    reasoning = usage.get("output_tokens_details", {}).get("reasoning_tokens", 0)
    in_rate, out_rate = PRICING.get(args.model, (0.0, 0.0))
    cost = tin / 1e6 * in_rate + tout / 1e6 * out_rate

    header = (
        f"<!-- generated by scripts/second_opinion.py — do not edit the body -->\n"
        f"# External second opinion — verbatim response\n\n"
        f"| field | value |\n|---|---|\n"
        f"| model | `{args.model}` |\n"
        f"| reasoning effort | `{args.effort}` |\n"
        f"| requested | {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC} |\n"
        f"| prompt | [`{args.prompt.split('/')[-1]}`]({args.prompt.split('/')[-1]}) |\n"
        f"| input tokens | {tin:,} |\n"
        f"| output tokens | {tout:,} (of which {reasoning:,} reasoning) |\n"
        f"| cost | ${cost:.2f} |\n"
        f"| status | `{payload.get('status')}` |\n\n"
        f"Everything below this line is the model's answer, unedited.\n\n---\n\n"
    )

    with open(args.out, "w") as fh:
        fh.write(header + text + "\n")

    print(f"wrote {args.out}")
    print(f"  status={payload.get('status')}  in={tin:,} out={tout:,} "
          f"(reasoning={reasoning:,})  cost=${cost:.2f}")


if __name__ == "__main__":
    main()
