// swift-tools-version:5.9
// Package manifest for VleThermo — the local Swift package that wraps the
// Rust vle engine (see IOS_FFI_PLAN.md and docs/en/ios/README.md).
//
// Layering (bottom → top):
//   VleFFI.xcframework   — the compiled Rust static libraries + C headers.
//                          GENERATED by scripts/build-ios.sh, not committed.
//   VleFFI binaryTarget  — exposes that C module to Swift.
//   VleThermo target     — the UniFFI-generated Swift wrapper
//                          (VleFFI.generated.swift, also generated) plus
//                          the hand-written sugar in Extensions.swift.
//   VleThermoTests       — XCTests that cross the real FFI boundary,
//                          running natively on this Mac (the macOS slice).
//
// If `swift build` fails with "does not contain expected binary artifact",
// you cloned fresh and haven't built the Rust side yet:
//   scripts/build-ios.sh

import PackageDescription

let package = Package(
    name: "VleThermo",
    platforms: [
        // Keep in sync with the deployment targets exported in
        // scripts/build-ios.sh.
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "VleThermo", targets: ["VleThermo"])
    ],
    targets: [
        .binaryTarget(name: "VleFFI", path: "VleFFI.xcframework"),
        .target(name: "VleThermo", dependencies: ["VleFFI"]),
        .testTarget(name: "VleThermoTests", dependencies: ["VleThermo"]),
    ]
)
