"""Tests for the Rust-side component database (M12.2, gap G3).

Two concerns live here, both about the *Rust* database exposed through the
wheel — distinct from ``test_db.py``, which covers the SQLite ``vle.db``:

1. **Drift guard** — the canonical ``engine/data/components.json`` (embedded
   into the crate via ``include_str!``) and the wheel copy
   ``python/src/vle/data/components.json`` must be **byte-identical**. Both are
   generated by ``scripts/build_components_json.py``; this test fails loudly if
   one is regenerated and the other isn't.
2. **Binding parity** — ``vle._engine.db_component`` / ``db_available`` (the
   PyO3 view of ``vle_thermo::db``) must agree with the JSON literals and with
   the pure-Python loader ``vle.components``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from vle import _engine

# ``python/tests/test_rust_db.py`` → parents[2] is the repo root. Both JSON
# copies live under it. In the day-to-day ``pytest`` run (and cibuildwheel,
# which copies the whole project into the build container) both are present.
_REPO = Path(__file__).resolve().parents[2]
_ENGINE_JSON = _REPO / "engine" / "data" / "components.json"
_WHEEL_JSON = _REPO / "python" / "src" / "vle" / "data" / "components.json"


def test_engine_and_wheel_json_byte_identical():
    """The two committed JSON copies must never drift apart."""
    if not _ENGINE_JSON.exists() or not _WHEEL_JSON.exists():
        pytest.skip("source-tree JSON copies not present in this environment")
    engine_bytes = _ENGINE_JSON.read_bytes()
    wheel_bytes = _WHEEL_JSON.read_bytes()
    assert engine_bytes == wheel_bytes, (
        "engine/data/components.json and python/src/vle/data/components.json "
        "differ — regenerate BOTH with scripts/build_components_json.py"
    )


def _json_compounds() -> dict:
    """The compound table the wheel ships (the byte-identical guard above
    proves this equals the engine copy)."""
    return json.loads(_WHEEL_JSON.read_text(encoding="utf-8"))["compounds"]


def test_db_component_matches_json_literals():
    """``db_component('toluene')`` must return the JSON's toluene numbers."""
    if not _WHEEL_JSON.exists():
        pytest.skip("source-tree JSON not present in this environment")
    ref = _json_compounds()["toluene"]
    got = _engine.db_component("toluene")
    assert got is not None
    assert got["tc"] == ref["tc"]
    assert got["pc"] == ref["pc"]
    assert got["omega"] == ref["omega"]
    # Coefficient lists are compared with a tolerance: serde_json (Rust) and
    # ``json`` (Python) are both correctly-rounded parsers, but the tiny
    # high-precision Cp fit coefficients can land 1 ULP apart between them.
    assert got["psat_coeffs"] == pytest.approx(ref["psat_coeffs"], rel=1e-12)
    assert got["cp_coeffs"] == pytest.approx(ref["cp_coeffs"], rel=1e-12)


def test_db_component_case_and_whitespace_insensitive():
    """Name normalization mirrors ``vle.components.get`` (trim + lower-case)."""
    a = _engine.db_component("water")
    b = _engine.db_component("  Water ")
    assert a is not None and b is not None
    assert a["tc"] == b["tc"]


def test_db_component_unknown_returns_none():
    """Unknowns — and shorthands the Python loader also rejects — miss."""
    assert _engine.db_component("unobtainium") is None
    assert _engine.db_component("H2O") is None


def test_db_available_matches_python_loader():
    """The Rust and pure-Python catalogs list the same 24 names, sorted."""
    from vle import components

    rust_names = _engine.db_available()
    assert rust_names == sorted(rust_names)
    assert len(rust_names) == 24
    assert rust_names == components.available()
